version: "3.0"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - db-data:/var/lib/mysql
    command: ['--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3307:3306
    networks:
      - test

  app:
    build: .
    restart: on-failure
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - test

volumes:
  db-data:
networks:
  test: